name: whistl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - absl-py=0.9.0
  - asn1crypto=1.3.0
  - atomicwrites=1.3.0
  - attrs=19.2.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - blinker=1.4
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cudnn=7.6.0
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - future=0.18.2
  - glib=2.56.2
  - gmp=6.1.2
  - google-auth=1.11.2
  - google-auth-oauthlib=0.4.1
  - graphite2=1.3.13
  - graphviz=2.40.1
  - grpcio=1.27.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - icu=58.2
  - idna=2.9
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.1.1
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.0
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm8=8.0.1
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.31.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mizani=0.6.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.1
  - numba=0.48.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - oauthlib=3.1.0
  - openssl=1.1.1f
  - packaging=19.2
  - palettable=3.3.0
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - pixman=0.38.0
  - plotnine=0.6.0
  - pluggy=0.13.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.11.4
  - ptyprocess=0.6.0
  - pudb=2019.2
  - py=1.8.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.19
  - pydot=1.4.1
  - pygments=2.4.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - pytest=5.2.2
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scikit-learn=0.22.1
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tensorboard=2.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.3
  - umap-learn=0.3.10
  - urllib3=1.25.8
  - urwid=2.1.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=1.0.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - python-graphviz==0.13
    - torchviz==0.0.1

